image:
  file: .gitpod.dockerfile
tasks:
- init: wget https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_linux_v1.7.8+hotfix.4-stable.tar.xz &&
        tar xf ./flutter_linux_v1.7.8+hotfix.4-stable.tar.xz && gp env -e PATH=`pwd`/flutter/bin